
spring:
  application:
    name: xrut
  datasource:
    url: jdbc:postgresql://localhost:5432/xrut
    username: postgres
    password: 2267
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port : 8089



logging:
  file:
    name: app.log